name: my_flutter_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  math_expressions: ^2.4.0
  provider: ^6.0.0
  fl_chart: ^0.40.0 # Use fl_chart for plotting
  url_launcher: ^6.0.3
  geolocator: ^7.6.2
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
